name: Accessibility CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  a11y:
    runs-on: ubuntu-latest
    env:
      BASE_URL: http://localhost:3000

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Generate route manifest
        run: npm run generate:routes

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start Next server
        run: nohup npx next start -p 3000 >/dev/null 2>&1 &

      - name: Wait for server
        run: |
          npx wait-on -t 60000 $BASE_URL

      - name: Playwright (axe serious/critical)
        run: npx playwright test
        continue-on-error: false

      - name: Pa11y CI (errors only)
        run: npm run test:pa11y
        continue-on-error: false

      - name: Lighthouse CI (A11y ≥ 0.95)
        run: npm run test:lhci
        continue-on-error: false

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload Pa11y report (ndjson)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pa11y-report
          path: pa11y-report.ndjson

      - name: Upload Lighthouse report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lhci-report
          path: lhci-report
